# Generated by Django 6.1.2 on 2026-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0003_receipt_purchase_date_and_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="receipts/%Y/%m/", verbose_name="Фото чека"
            ),
        ),
    ]
